# Generated by Django 5.0.6 on 2024-05-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tools_rename_is_superuser_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
