# Generated by Django 5.0.6 on 2024-06-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tools_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='updation_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updation_time',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='tools',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
