# Generated by Django 5.0.6 on 2024-06-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_creation_time_tools_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='tool_name',
            new_name='name',
        ),
    ]
