# Generated by Django 5.0.6 on 2024-06-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tool_name_tools_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
